export const DEFAULT_MENU_CATALOGUE = [
  { id: 'item-1', name: 'Paneer Tikka', price: 260, category: 'North Indian', description: 'Clay oven cooked cottage cheese cubes', diet: 'VEG', image: '/images/Menu_Items/paneer_tikka.png', isVisible: true, isOutOfStock: false, prepTime: 20, isPopular: true, rating: 4.8 },
  { id: 'item-2', name: 'Butter Chicken', price: 340, category: 'North Indian', description: 'Tender chicken in rich creamy tomato gravy', diet: 'NON-VEG', image: '/images/Menu_Items/butter_chicken.png', isVisible: true, isOutOfStock: false, prepTime: 25, isPopular: true, rating: 4.9 },
  { id: 'item-3', name: 'Veg Hakka Noodles', price: 180, category: 'Chinese', description: 'Stir-fried noodles with garden fresh vegetables', diet: 'VEG', image: '/images/Menu_Items/veg_noodles.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: false, rating: 4.3 },
  { id: 'item-4', name: 'Manchurian Gravy', price: 210, category: 'Chinese', description: 'Vegetable dumplings in spicy soy garlic sauce', diet: 'VEG', image: '/images/Menu_Items/manchurian.png', isVisible: true, isOutOfStock: false, prepTime: 20, isPopular: true, rating: 4.5 },
  { id: 'item-5', name: 'Cold Coffee', price: 120, category: 'Beverages', description: 'Creamy espresso shake served chilled', diet: 'VEG', image: '/images/Menu_Items/cold_coffee.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: true, rating: 4.7 },
  { id: 'item-6', name: 'Chocolate Brownie', price: 150, category: 'Desserts', description: 'Warm fudgy brownie with chocolate syrup', diet: 'VEG', image: '/images/Menu_Items/chocolate_brownie.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: false, rating: 4.6 },
  
  // North Indian Main Course
  { id: 'item-7', name: 'Dal Makhani', price: 220, category: 'North Indian', description: 'Slow cooked black lentils with butter and cream', diet: 'VEG', image: '/images/Menu_Items/dal_makhani.png', isVisible: true, isOutOfStock: false, prepTime: 30, isPopular: true, rating: 4.8 },
  { id: 'item-8', name: 'Kadai Paneer', price: 280, category: 'North Indian', description: 'Paneer cooked with bell peppers and ground spices', diet: 'VEG', image: '/images/Menu_Items/kadai_paneer.png', isVisible: true, isOutOfStock: false, prepTime: 25, isPopular: false, rating: 4.4 },
  { id: 'item-9', name: 'Chicken Tikka Masala', price: 350, category: 'North Indian', description: 'Roasted chicken chunks in spicy sauce', diet: 'NON-VEG', image: '/images/Menu_Items/chicken_tikka_masala.png', isVisible: true, isOutOfStock: false, prepTime: 25, isPopular: true, rating: 4.7 },
  { id: 'item-10', name: 'Garlic Naan', price: 60, category: 'North Indian', description: 'Soft flatbread topped with garlic and butter', diet: 'VEG', image: '/images/Menu_Items/garlic_naan.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: true, rating: 4.9 },
  { id: 'item-11', name: 'Jeera Rice', price: 140, category: 'North Indian', description: 'Basmati rice flavored with cumin seeds', diet: 'VEG', image: '/images/Menu_Items/jeera_rice.png', isVisible: true, isOutOfStock: false, prepTime: 20, isPopular: false, rating: 4.2 },
  { id: 'item-12', name: 'Mutton Rogan Josh', price: 420, category: 'North Indian', description: 'Aromatic lamb dish of Persian origin', diet: 'NON-VEG', image: '/images/Menu_Items/mutton_rogan_josh.png', isVisible: true, isOutOfStock: false, prepTime: 40, isPopular: true, rating: 4.8 },
  { id: 'item-13', name: 'Palak Paneer', price: 260, category: 'North Indian', description: 'Cottage cheese cubes in smooth spinach puree', diet: 'VEG', image: '/images/Menu_Items/palak_paneer.png', isVisible: true, isOutOfStock: false, prepTime: 25, isPopular: false, rating: 4.5 },
  { id: 'item-14', name: 'Chicken Biryani', price: 320, category: 'North Indian', description: 'Fragrant basmati rice cooked with marinated chicken', diet: 'NON-VEG', image: '/images/Menu_Items/chicken_biryani.png', isVisible: true, isOutOfStock: false, prepTime: 35, isPopular: true, rating: 4.9 },
  { id: 'item-15', name: 'Tandoori Roti', price: 30, category: 'North Indian', description: 'Whole wheat flatbread baked in a tandoor', diet: 'VEG', image: '/images/Menu_Items/tandoori_roti.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: true, rating: 4.8 },
  
  // Chinese
  { id: 'item-16', name: 'Spring Rolls', price: 150, category: 'Chinese', description: 'Crispy rolls stuffed with mixed vegetables', diet: 'VEG', image: '/images/Menu_Items/spring_rolls.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: false, rating: 4.4 },
  { id: 'item-17', name: 'Chilli Chicken Dry', price: 290, category: 'Chinese', description: 'Crispy chicken tossed in spicy chilli sauce', diet: 'NON-VEG', image: '/images/Menu_Items/chilli_chicken_dry.png', isVisible: true, isOutOfStock: false, prepTime: 20, isPopular: true, rating: 4.6 },
  { id: 'item-18', name: 'Veg Fried Rice', price: 170, category: 'Chinese', description: 'Classic wok-tossed rice with mixed vegetables', diet: 'VEG', image: '/images/Menu_Items/veg_fried_rice.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: false, rating: 4.3 },
  { id: 'item-19', name: 'Gobi Manchurian', price: 190, category: 'Chinese', description: 'Crispy cauliflower florets in soy garlic sauce', diet: 'VEG', image: '/images/Menu_Items/gobi_manchurian.png', isVisible: true, isOutOfStock: false, prepTime: 20, isPopular: true, rating: 4.5 },
  { id: 'item-20', name: 'Chicken Sweet Corn Soup', price: 140, category: 'Chinese', description: 'Comforting thick soup with chicken and corn', diet: 'NON-VEG', image: '/images/Menu_Items/chicken_corn_soup.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: false, rating: 4.4 },
  { id: 'item-21', name: 'Chilli Paneer', price: 240, category: 'Chinese', description: 'Cottage cheese cubes tossed in spicy sauce', diet: 'VEG', image: '/images/Menu_Items/chilli_paneer.png', isVisible: true, isOutOfStock: false, prepTime: 20, isPopular: true, rating: 4.6 },
  
  // Fast Food
  { id: 'item-22', name: 'French Fries', price: 100, category: 'Fast Food', description: 'Crispy golden potato fries', diet: 'VEG', image: '/images/Menu_Items/french_fries.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: true, rating: 4.7 },
  { id: 'item-23', name: 'Chicken Burger', price: 160, category: 'Fast Food', description: 'Juicy chicken patty with fresh lettuce and mayo', diet: 'NON-VEG', image: '/images/Menu_Items/chicken_burger.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: false, rating: 4.4 },
  { id: 'item-24', name: 'Veggie Wrap', price: 130, category: 'Fast Food', description: 'Tortilla wrap filled with assorted veggies and sauce', diet: 'VEG', image: '/images/Menu_Items/veggie_wrap.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: false, rating: 4.3 },
  { id: 'item-25', name: 'Classic Veg Burger', price: 120, category: 'Fast Food', description: 'Crispy veg patty with fresh lettuce and mayo', diet: 'VEG', image: '/images/Menu_Items/classic_veg_burger.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: true, rating: 4.5 },
  { id: 'item-26', name: 'Chicken Nuggets', price: 180, category: 'Fast Food', description: 'Bite-sized breaded chicken pieces', diet: 'NON-VEG', image: '/images/Menu_Items/chicken_nuggets.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: true, rating: 4.6 },
  { id: 'item-27', name: 'Cheese Pizza', price: 220, category: 'Fast Food', description: 'Classic pizza with tomato sauce and mozzarella cheese', diet: 'VEG', image: '/images/Menu_Items/cheese_pizza.png', isVisible: true, isOutOfStock: false, prepTime: 20, isPopular: false, rating: 4.4 },
  { id: 'item-28', name: 'Margherita Pizza', price: 250, category: 'Fast Food', description: 'Classic pizza with tomato sauce and mozzarella', diet: 'VEG', image: '/images/Menu_Items/margherita_pizza.png', isVisible: true, isOutOfStock: false, prepTime: 20, isPopular: true, rating: 4.6 },
  
  // Beverages
  { id: 'item-29', name: 'Sweet Lassi', price: 80, category: 'Beverages', description: 'Traditional yogurt-based sweet drink', diet: 'VEG', image: '/images/Menu_Items/sweet_lassi.png', isVisible: true, isOutOfStock: false, prepTime: 5, isPopular: true, rating: 4.7 },
  { id: 'item-30', name: 'Masala Chai', price: 40, category: 'Beverages', description: 'Indian spiced milk tea', diet: 'VEG', image: '/images/Menu_Items/masala_chai.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: true, rating: 4.8 },
  { id: 'item-31', name: 'Mango Lassi', price: 90, category: 'Beverages', description: 'Sweet yogurt drink blended with mango pulp', diet: 'VEG', image: '/images/Menu_Items/mango_lassi.png', isVisible: true, isOutOfStock: false, prepTime: 5, isPopular: true, rating: 4.8 },
  { id: 'item-32', name: 'Fresh Lime Soda', price: 70, category: 'Beverages', description: 'Refreshing fizzy drink with lemon and mint', diet: 'VEG', image: '/images/Menu_Items/fresh_lime_soda.png', isVisible: true, isOutOfStock: false, prepTime: 5, isPopular: false, rating: 4.5 },
  { id: 'item-33', name: 'Iced Tea', price: 90, category: 'Beverages', description: 'Chilled tea with lemon flavor', diet: 'VEG', image: '/images/Menu_Items/iced_tea.png', isVisible: true, isOutOfStock: false, prepTime: 5, isPopular: false, rating: 4.4 },
  { id: 'item-34', name: 'Cold Brew Coffee', price: 130, category: 'Beverages', description: 'Smooth, cold-steeped coffee', diet: 'VEG', image: '/images/Menu_Items/cold_brew.png', isVisible: true, isOutOfStock: false, prepTime: 5, isPopular: true, rating: 4.6 },
  
  // Desserts
  { id: 'item-35', name: 'Rasmalai', price: 120, category: 'Desserts', description: 'Soft cottage cheese discs in thickened sweet milk', diet: 'VEG', image: '/images/Menu_Items/rasmalai.png', isVisible: true, isOutOfStock: false, prepTime: 5, isPopular: true, rating: 4.9 },
  { id: 'item-36', name: 'Vanilla Ice Cream', price: 90, category: 'Desserts', description: 'Classic creamy vanilla ice cream', diet: 'VEG', image: '/images/Menu_Items/vanilla_ice_cream.png', isVisible: true, isOutOfStock: false, prepTime: 5, isPopular: false, rating: 4.5 },
  { id: 'item-37', name: 'Gulab Jamun', price: 80, category: 'Desserts', description: 'Deep-fried milk dumplings soaked in sugar syrup', diet: 'VEG', image: '/images/Menu_Items/gulab_jamun.png', isVisible: true, isOutOfStock: false, prepTime: 5, isPopular: true, rating: 4.9 },
  { id: 'item-38', name: 'Gajar Ka Halwa', price: 110, category: 'Desserts', description: 'Traditional carrot pudding with nuts and ghee', diet: 'VEG', image: '/images/Menu_Items/gajar_halwa.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: true, rating: 4.8 },
  { id: 'item-39', name: 'Fruit Salad', price: 100, category: 'Desserts', description: 'Assorted fresh seasonal fruits', diet: 'VEG', image: '/images/Menu_Items/fruit_salad.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: false, rating: 4.4 },
  { id: 'item-40', name: 'Cheesecake', price: 200, category: 'Desserts', description: 'New York style baked cheesecake', diet: 'VEG', image: '/images/Menu_Items/cheesecake.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: true, rating: 4.7 },
  
  // South Indian
  { id: 'item-41', name: 'Masala Dosa', price: 140, category: 'South Indian', description: 'Crispy crepe filled with spiced potato mash', diet: 'VEG', image: '/images/Menu_Items/masala_dosa.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: true, rating: 4.8 },
  { id: 'item-42', name: 'Idli Sambar', price: 90, category: 'South Indian', description: 'Steamed rice cakes served with lentil soup', diet: 'VEG', image: '/images/Menu_Items/idli_sambar.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: true, rating: 4.6 },
  { id: 'item-43', name: 'Medu Vada', price: 110, category: 'South Indian', description: 'Crispy lentil doughnuts served with chutney', diet: 'VEG', image: '/images/Menu_Items/medu_vada.png', isVisible: true, isOutOfStock: false, prepTime: 10, isPopular: false, rating: 4.5 },
  { id: 'item-44', name: 'Rava Onion Dosa', price: 160, category: 'South Indian', description: 'Semolina crepe topped with chopped onions', diet: 'VEG', image: '/images/Menu_Items/rava_onion_dosa.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: true, rating: 4.6 },
  { id: 'item-45', name: 'Uttapam', price: 130, category: 'South Indian', description: 'Thick pancake topped with mixed vegetables', diet: 'VEG', image: '/images/Menu_Items/uttapam.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: false, rating: 4.4 },
  
  // Healthy
  { id: 'item-46', name: 'Grilled Chicken Salad', price: 240, category: 'Healthy', description: 'Fresh greens with grilled chicken breast and vinaigrette', diet: 'NON-VEG', image: '/images/Menu_Items/chicken_salad.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: true, rating: 4.7 },
  { id: 'item-47', name: 'Quinoa Bowl', price: 280, category: 'Healthy', description: 'Nutritious quinoa with roasted veggies and hummus', diet: 'VEG', image: '/images/Menu_Items/quinoa_bowl.png', isVisible: true, isOutOfStock: false, prepTime: 15, isPopular: false, rating: 4.6 }
];
